// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnB6YEObwWrPxh2QgMKKku4G9N7gP2NuA',
    appId: '1:207857875468:web:dcc7cecbd153d019870c29',
    messagingSenderId: '207857875468',
    projectId: 'trail-safe-8933a',
    authDomain: 'trail-safe-8933a.firebaseapp.com',
    storageBucket: 'trail-safe-8933a.firebasestorage.app',
    measurementId: 'G-9N5WD7VRTV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2LRfVugCu_dQJnTjIkO1BqFSFTeVFfOE',
    appId: '1:207857875468:android:465b1cedf803b460870c29',
    messagingSenderId: '207857875468',
    projectId: 'trail-safe-8933a',
    storageBucket: 'trail-safe-8933a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCnI7fRXeWp7VrYz9VomVhOJTGghB85e8U',
    appId: '1:207857875468:ios:89516f4d650af7cf870c29',
    messagingSenderId: '207857875468',
    projectId: 'trail-safe-8933a',
    storageBucket: 'trail-safe-8933a.firebasestorage.app',
    iosBundleId: 'com.example.ecoTourism',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCnI7fRXeWp7VrYz9VomVhOJTGghB85e8U',
    appId: '1:207857875468:ios:89516f4d650af7cf870c29',
    messagingSenderId: '207857875468',
    projectId: 'trail-safe-8933a',
    storageBucket: 'trail-safe-8933a.firebasestorage.app',
    iosBundleId: 'com.example.ecoTourism',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnB6YEObwWrPxh2QgMKKku4G9N7gP2NuA',
    appId: '1:207857875468:web:6cc19e4d01a1dbd6870c29',
    messagingSenderId: '207857875468',
    projectId: 'trail-safe-8933a',
    authDomain: 'trail-safe-8933a.firebaseapp.com',
    storageBucket: 'trail-safe-8933a.firebasestorage.app',
    measurementId: 'G-3CPF4FHFS0',
  );
}
