import 'package:flutter/material.dart';
import 'screens/home_screen.dart';
import 'screens/main_screen.dart';
import 'screens/trek_details.dart';
import 'screens/eco_calculator.dart';
import 'screens/navigation_screen.dart';
// import 'package:flutter/material.dart';
import 'package:firebase_core/firebase_core.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import 'firebase_options.dart'; // 🔥 generated by flutterfire

Future<void> _logFirestoreConnectionStatus() async {
  try {
    final snapshot = await FirebaseFirestore.instance
        .collection('trails')
        .limit(1)
        .get();

    debugPrint(
      '[FIRESTORE CHECK] Connected successfully. trails docs fetched: ${snapshot.docs.length}',
    );

    if (snapshot.docs.isNotEmpty) {
      debugPrint('[FIRESTORE CHECK] First trail data: ${snapshot.docs.first.data()}');
    } else {
      debugPrint('[FIRESTORE CHECK] trails collection is reachable but empty.');
    }
  } on FirebaseException catch (e) {
    debugPrint('[FIRESTORE CHECK] FirebaseException code=${e.code} message=${e.message}');
  } catch (e) {
    debugPrint('[FIRESTORE CHECK] Unknown error: $e');
  }
}

void main() async {
  WidgetsFlutterBinding.ensureInitialized();

  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );

  await _logFirestoreConnectionStatus();

  runApp(const MyApp());
}

class MyApp extends StatelessWidget {
  const MyApp({super.key});

  @override
  Widget build(BuildContext context) {
    return const MaterialApp(
      debugShowCheckedModeBanner: false,
      home: NavigationScreen(),
      // home: TrekDetails(),
      // home: EcoCalculator(),
    );
  }
}